name: Docker

on:
  workflow_call: 

jobs:

  docker:
    runs-on: ubuntu-lantest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Docker build 
      uses: docker/setup-buildx-action@v3.0.0 
    
